[package]
name = "wesl_linker"
version = "0.1.0"
edition = "2024"

[dependencies]
arcstr = "1.2.0"
indexmap = "2.10.0"
slotmap = "1.0.7"
sourcemap = { version = "9.2.2", optional = true }
thiserror = "2.0.12"
winnow = { version = "0.7.11", default-features = false, features = ["alloc"] }

[dev-dependencies]
proptest = "1.7.0"
test-strategy = "0.4.3"

[features]
debug = []
default = ["debug", "fs"]
fs = []
source_map = ["dep:sourcemap"]
trace = ["winnow/debug"]
